apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deploy
spec: 
    replicas: 1
    selector:
        matchLabels:
            app: mysql 
    strategy: 
        type: Recreate 
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql:8.0
                  env:
                    - name: MYSQL_ROOT_PASSWORD 
                      valueFrom:
                        secretKeyRef:
                            name: mysql-db-pwd
                            key: db-password
                  ports:
                    - containerPort: 3306
                  volumeMounts:
                    - name: pvc-mysql
                      mountPath: /var/lib/mysql
                    - name: dbcreation-script
                      mountPath: /docker-entrypoint-initdb.d
            volumes: 
                - name: pvc-mysql 
                  persistentVolumeClaim:
                    claimName: pvc-mysql-ebs 
                - name: dbcreation-script 
                  configMap:
                    name: cm-dbcreation-script
