apiVersion: apps/v1
kind: Deployment 
metadata:
  name: usermgmt-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt
  template:  
    metadata:
      labels: 
        app: usermgmt
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e " >> MYSQL DB Server has started";']
      containers:
        - name: usermgmt-app
          image: stacksimplify/kube-usermanagement-microservice:1.0.0
          ports: 
            - containerPort: 8095           
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "usermgmt"            
            - name: DB_USERNAME
              value: "root"            
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-pwd
                  key: db-password           
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c 
                - nc -z localhost 8095
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /usermgmt/health-status
              port: 8095
            initialDelaySeconds: 60
            periodSeconds: 10